dist: xenial
services:
- postgresql
addons:
postgresql: '9.4'
before_script:
- psql -U postgres -c "create user examenfebrero password 'examenfebrero'"
- psql -U postgres -c "create database examenfebrerodb owner examenfebrero"
- psql -U postgres -c "ALTER USER examenfebrero CREATEDB"
language: python
python:
- '3.6'
<<<<<<< HEAD
branches:
only:
- master
=======
>>>>>>> desarrollo
install:
- pip install -r requirements.txt
script:
- cd decide
<<<<<<< HEAD
- python ./manage.py test
=======
- python ./manage.py test store
>>>>>>> desarrollo
